#include "core/backends/anan/AnanDroopDefaults.h"

#include "core/backends/anan/P2Protocol.h"

#include <algorithm>
#include <array>

namespace AetherSDR::anan {
namespace {

// Pure data, generated by tools/derive_droop_from_gateware.py. Kept in its own
// file so regenerating it cannot clobber the lookup below.
#include "core/backends/anan/AnanDroopDefaultTables.inc"

// The .inc emits std::array<float, 1024>, which IS DroopCorrectionTable --
// assert rather than assume, so a regeneration at a different bin count is a
// compile error here instead of a silent no-op at apply time (see
// applyDroopCorrectionDb()'s own size handling).
static_assert(kDroopCorrectionGw27.size() == kDroopCorrectionFftSize,
              "generated default table must match the droop storage grid");

}  // namespace

const DroopCorrectionTable* defaultDroopTableForRate(int rateKsps) noexcept
{
    // One table serves every rate; the lookup exists to reject rates this
    // radio cannot run, not to choose between curves. See the header.
    // kDdc0RatesKsps, not a local copy: AnanRxDsp::setDroopCorrectionTable()
    // validates against that same list, so a seventh rate added there but not
    // here would be accepted by the DSP while this returned nullptr for it --
    // the rate would ship with no default and nothing would fail.
    return std::find(kDdc0RatesKsps.begin(), kDdc0RatesKsps.end(), rateKsps)
            != kDdc0RatesKsps.end()
        ? &kDroopCorrectionGw27
        : nullptr;
}

const std::array<int, 6>& defaultDroopRatesKsps() noexcept
{
    return kDdc0RatesKsps;
}

}  // namespace AetherSDR::anan
