#include "core/LpMeterProtocol.h"

#include <QByteArray>
#include <QList>
#include <QString>

#include <cmath>
#include <cstdio>

using namespace AetherSDR::LpMeter;

namespace {

int g_failed = 0;

void report(const char* name, bool ok)
{
    std::printf("%s %s\n", ok ? "[ OK ]" : "[FAIL]", name);
    if (!ok) {
        ++g_failed;
    }
}

bool near(double a, double b, double tol = 1e-6)
{
    return std::fabs(a - b) <= tol;
}

// Verbatim from the manufacturer's manual, p.21 -- quoted, not generated by
// our own encoder, which is the property that lets it catch a real bug.
// NOTE: 41 characters, because the manual's Z field is 4 wide where the wire
// sends 5. It must still decode: field-shape validation, not length, is the
// rule. See kRecordLength.
const char kManualExample[] = "1457.00,49.3,005.0,2,N8LP  ,0,2,61.6,1.02";

// Captured off real hardware 2026-08-29 (idle). 42 characters.
const char kCapturedIdle[] = "0000.00,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00";

// Captured under drive, same session: ~8.85 W into a 1.68 SWR load. Negative
// dBm is what the meter reports at idle, so an unsigned parse would pass every
// synthetic test and fail on the very first real record.
const char kCapturedTx[] = "0008.85,047.1,028.5,0,NF0T  ,2,1,39.4,1.68";

// The ser2net connect banner arrives before any record and contains no
// marker. Representative of the real one's shape.
const char kBanner[] =
    "\r\nser2net port tcp,2000 device serialdev, /dev/serial/by-id/usb-serial0,"
    " 115200n81,local -rtscts [115200N81,CLOCAL,HANGUP_WHEN_DONE]"
    " (Debian GNU/Linux)\r\n\r\n";

QByteArray rec(const char* body)
{
    return QByteArray(1, kRecordMarker) + QByteArray(body);
}

QList<Reading> drain(const QByteArray& bytes)
{
    QList<Reading> out;
    ResponseParser p;
    p.setReadingCallback([&](const Reading& r) { out.append(r); });
    p.feed(bytes);
    return out;
}

}  // namespace

int main()
{
    // ---- decode: the manual's own example -------------------------------
    {
        const auto r = decodeReading(kManualExample);
        report("manual's literal example decodes (41 chars, Z field short)",
               r.has_value()
                   && near(r->powerW, 1457.00)
                   && near(r->zOhms, 49.3)
                   && near(r->phaseDeg, 5.0)
                   && r->alarmSetPoint == 2
                   && r->callsign == QStringLiteral("N8LP")
                   && r->powerRange == 0
                   && r->peakHoldMode == 2
                   && near(r->dBm, 61.6)
                   && near(r->swr, 1.02));
    }

    // ---- decode: the hardware capture ------------------------------------
    {
        const auto r = decodeReading(kCapturedIdle);
        report("captured idle record decodes byte-for-byte",
               r.has_value()
                   && near(r->powerW, 0.0)
                   && near(r->zOhms, 46.3)
                   && near(r->phaseDeg, 88.5)
                   && r->alarmSetPoint == 0
                   && r->callsign == QStringLiteral("NF0T")
                   && r->powerRange == 2
                   && r->peakHoldMode == 1
                   && near(r->dBm, -2.3)
                   && near(r->swr, 1.00));
        report("NEGATIVE dBm parses (what the meter reports at idle)",
               r.has_value() && r->dBm < 0.0);
    }
    {
        const auto r = decodeReading(kCapturedTx);
        report("captured transmit record decodes",
               r.has_value() && near(r->powerW, 8.85) && near(r->swr, 1.68)
                   && near(r->dBm, 39.4));
    }

    // ---- physics cross-check --------------------------------------------
    // |Z| and phase must reproduce the SWR the meter itself reports. This
    // validates the field interpretation against physics rather than against
    // another document -- and it is what caught the key-up incoherence when
    // it was first run across a whole capture.
    {
        const auto r = decodeReading(kCapturedTx);
        bool ok = r.has_value();
        if (ok) {
            const double th = r->phaseDeg * M_PI / 180.0;
            const double re = r->zOhms * std::cos(th);
            const double im = r->zOhms * std::sin(th);
            const double nr = re - 50.0;
            const double dr = re + 50.0;
            const double g = std::sqrt((nr * nr + im * im) / (dr * dr + im * im));
            const double swr = (1.0 + g) / (1.0 - g);
            ok = near(swr, r->swr, 0.01);
        }
        report("|Z|/phase reproduce the meter's own SWR to 0.01", ok);
    }

    // ---- field coherence -------------------------------------------------
    // A record is NOT a snapshot: at key-up in Peak Hold the meter holds
    // power and dBm ~1.7 s while Z/phase/SWR have already reverted. Detected
    // from physics, so it covers Avg mode's own hold too -- which gating on
    // the peakHoldMode field would miss.
    {
        const auto r = decodeReading(kCapturedTx);
        report("a coherent transmit record is flagged coherent",
               r.has_value() && r->coherent);
    }
    {
        // Captured verbatim during a key-up transient: real power alongside
        // SWR 1.00 and an idle-looking phase.
        const auto r = decodeReading("0008.77,046.3,087.3,0,NF0T  ,2,1,39.4,1.00");
        report("a captured key-up transient is flagged INCOHERENT",
               r.has_value() && !r->coherent);
    }
    {
        const auto r = decodeReading(kCapturedIdle);
        report("idle records are not judged incoherent (no RF to measure)",
               r.has_value() && r->coherent);
    }
    report("swrFromImpedance: 50 ohms at 0 deg is a perfect match",
           near(swrFromImpedance(50.0, 0.0), 1.0, 1e-6));
    report("swrFromImpedance reproduces the captured record's own SWR",
           near(swrFromImpedance(47.1, 28.5), 1.68, 0.01));

    // ---- validation: stricter than a length check ------------------------
    report("valid captured record accepted", looksLikeRecord(kCapturedIdle));
    report("wrong field count rejected",
           !looksLikeRecord("0000.00,046.3,088.5,0,NF0T  ,2,1,-2.3"));
    report("non-numeric power rejected",
           !looksLikeRecord("00X0.00,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
    report("SWR below 1.0 rejected (physically impossible)",
           !looksLikeRecord("0000.00,046.3,088.5,0,NF0T  ,2,1,-2.3,0.50"));
    report("negative power rejected",
           !looksLikeRecord("-001.00,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
    report("phase beyond 90 deg rejected",
           !looksLikeRecord("0000.00,046.3,128.5,0,NF0T  ,2,1,-2.3,1.00"));
    report("non-digit enum field rejected",
           !looksLikeRecord("0000.00,046.3,088.5,X,NF0T  ,2,1,-2.3,1.00"));
    report("control byte in callsign rejected",
           !looksLikeRecord(QByteArray("0000.00,046.3,088.5,0,NF\nT  ,2,1,-2.3,1.00")));
    report("markup punctuation in callsign rejected",
           !looksLikeRecord("0000.00,046.3,088.5,0,<B>   ,2,1,-2.3,1.00"));
    // 42 characters with a separator in the wrong place: exactly the class of
    // corruption a `length == 42` test accepts and puts on a gauge.
    report("42 chars but misplaced separators rejected",
           !looksLikeRecord("0000.0,0046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
    // A wider dBm field is not this firmware, but must not be rejected by a
    // hard length rule -- that would reject every record such a unit sends.
    report("43-char record with a wider dBm field still accepted",
           looksLikeRecord("0000.00,046.3,088.5,0,NF0T  ,2,1,-12.3,1.00"));

    // ---- streaming -------------------------------------------------------
    {
        const auto got = drain(rec(kCapturedIdle));
        report("a single complete record emits without waiting for the next marker",
               got.size() == 1);
    }
    {
        const auto got = drain(QByteArray(kBanner) + rec(kCapturedIdle)
                               + rec(kCapturedTx));
        report("ser2net banner discarded, both records emitted",
               got.size() == 2 && near(got.at(1).powerW, 8.85));
    }
    {
        QList<Reading> out;
        ResponseParser p;
        p.setReadingCallback([&](const Reading& r) { out.append(r); });
        const QByteArray whole = rec(kCapturedIdle);
        p.feed(whole.left(20));
        const bool nothingYet = out.isEmpty();
        p.feed(whole.mid(20));
        report("record split across two feeds emits exactly once",
               nothingYet && out.size() == 1);
    }
    {
        const auto got = drain(QByteArray("garbage,not,a,record")
                               + rec(kCapturedIdle));
        report("leading garbage before the first marker is dropped",
               got.size() == 1);
    }
    {
        const auto got = drain(rec(kCapturedIdle) + "\r\n" + rec(kCapturedTx)
                               + "\r\n" + rec(kCapturedIdle));
        report("trailing CR/LF tolerated even though this firmware sends none",
               got.size() == 3);
    }
    {
        const auto got = drain(QByteArray(";;;;") + rec(kCapturedIdle));
        report("a run of bare markers resyncs without emitting", got.size() == 1);
    }
    {
        ResponseParser p;
        int n = 0;
        p.setReadingCallback([&](const Reading&) { ++n; });
        p.feed(rec(kCapturedIdle));
        p.reset();
        p.feed(QByteArray(kCapturedTx));  // no marker: must not decode
        report("reset() drops buffered state", n == 1);
    }

    // ---- enum names ------------------------------------------------------
    // Both tables were confirmed on hardware by cycling 'A' and 'F' through
    // full rotations: alarm walks 0..5, peak-hold walks 0..2. The manual lists
    // only 0..4 and 0..1, so these upper values are the ones a manual-derived
    // implementation would render blank.
    report("alarm names cover all six hardware-confirmed values",
           alarmSetPointName(0) == QStringLiteral("Off")
               && alarmSetPointName(4) == QStringLiteral("3.0")
               && alarmSetPointName(5) == QStringLiteral("User"));
    report("peak-hold names cover all three hardware-confirmed modes",
           peakHoldModeName(0) == QStringLiteral("Avg")
               && peakHoldModeName(1) == QStringLiteral("Peak")
               && peakHoldModeName(2) == QStringLiteral("Fast"));
    report("range names", powerRangeName(0) == QStringLiteral("High")
               && powerRangeName(2) == QStringLiteral("Low"));
    report("unknown enum values render readably, never blank",
           !alarmSetPointName(9).isEmpty() && alarmSetPointName(9).contains('9')
               && !powerRangeName(7).isEmpty()
               && !peakHoldModeName(7).isEmpty());

    // ---- derived values --------------------------------------------------
    // Was pinned at 0.0 dB, which is the value for TOTAL REFLECTION -- the
    // test protected the bug rather than catching it. A perfect match
    // reflects nothing, so the return loss is unbounded.
    report("return loss is +infinity at SWR 1.0 (a perfect match)",
           std::isinf(returnLossDb(1.0)) && returnLossDb(1.0) > 0.0);
    report("return loss is monotonic: a near-match is LARGE, not small",
           returnLossDb(1.001) > 60.0 && returnLossDb(1.001) > returnLossDb(3.0));
    report("return loss approaches 0 dB as SWR diverges (total reflection)",
           returnLossDb(1e9) < 0.001 && returnLossDb(1e9) >= 0.0);
    report("the reportable ceiling is the SWR field's own quantisation",
           near(maxReportableReturnLossDb(), 52.06, 0.05));
    report("return loss at SWR 3.0 is ~6.02 dB",
           near(returnLossDb(3.0), 6.0206, 1e-3));
    report("reflected power is 0 W at a perfect match",
           near(reflectedWattsFromSwr(100.0, 1.0), 0.0));
    report("reflected power at SWR 3.0 / 100 W is 25 W",
           near(reflectedWattsFromSwr(100.0, 3.0), 25.0, 1e-9));

    // ---- PollGate --------------------------------------------------------
    // THE regression test for the coupling defect: our own replies must never
    // move the suppression timestamp, or the solo poll rate silently collapses
    // to the suppression threshold.
    {
        PollGate g;
        qint64 now = 0;
        int polls = 0;
        for (int i = 0; i < 100; ++i) {          // 10 s at a 100 ms tick
            if (g.shouldPoll(now)) {
                ++polls;
                g.onRecord(now + 5);             // our reply, 5 ms later
            }
            now += PollGate::kSoloPollIntervalMs;
        }
        report("solo: polls every tick (own replies must not suppress)",
               polls == 100 && !g.isRidingAlong());
    }
    {
        // Foreign poller at the measured 100 ms cadence.
        PollGate g;
        qint64 now = 100;
        int polls = 0;
        for (int i = 0; i < 100; ++i) {
            g.onRecord(now - 50);                // foreign, off our tick phase
            if (g.shouldPoll(now)) { ++polls; }
            now += 100;
        }
        report("foreign 100 ms cadence: zero polls sent", polls == 0);
    }
    {
        // A 1 s foreign cadence -- inside the band the ADAPTIVE threshold
        // buys over a fixed 130 ms constant, which would poll ~8x between
        // every pair of foreign records here.
        //
        // Note the startup burst: the cadence is unknown until two foreign
        // records have been seen, so the floor applies for the first ~1 s and
        // a handful of polls escape. Bounded, once per connect, self-
        // correcting -- the alternative (assume slow until proven fast) would
        // stall real data at connect, which is worse.
        PollGate g;
        qint64 now = 0;
        int early = 0;
        int late = 0;
        for (int i = 0; i < 200; ++i) {
            if (now % 1000 == 0) { g.onRecord(now); }
            if (g.shouldPoll(now)) {
                (now < 2000 ? early : late)++;
                g.onRecord(now + 5);             // reply to the poll we sent
            }
            now += 100;
        }
        report("foreign 1 s cadence: fully suppressed once the cadence is learned",
               late == 0 && g.foreignIntervalMs() >= 900);
        report("  ... and the threshold covers the jitter tail, not just the mean",
               g.quietThresholdMs() >= 2 * g.foreignIntervalMs()
                   || g.quietThresholdMs() == PollGate::kMaxQuietMs);
        report("  ... after a bounded startup burst while it is still unknown",
               early > 0 && early < 12);
    }
    {
        // Past the ceiling we deliberately supplement rather than let our own
        // gauge follow a very slow client down. This is the same trade the
        // review flagged against its fixed 130 ms constant -- the adaptive
        // threshold moves the line from 130 ms to 2 s rather than removing
        // it, so it strictly dominates (everything the fixed constant
        // suppresses, plus the 130 ms - 2 s band) without claiming to
        // suppress everything. A STATED DECISION, pinned so it cannot drift
        // into being an accident: TelePost's own VCP offers up to 5 s, and
        // riding along there would mean a 0.2 Hz gauge.
        PollGate g;
        qint64 now = 0;
        int polls = 0;
        for (int i = 0; i < 300; ++i) {
            if (now % 5000 == 0) { g.onRecord(now); }
            if (g.shouldPoll(now)) {
                ++polls;
                g.onRecord(now + 5);             // reply to the poll we sent
            }
            now += 100;
        }
        report("foreign 5 s cadence is NOT suppressed (2 s ceiling, by design)",
               polls > 100);
    }
    {
        PollGate g;
        g.shouldPoll(1000);
        g.onRecord(1250);                        // delayed remote/VPN reply
        const bool ownNotForeign = (g.foreignIntervalMs() < 0);
        report("the first reply after our poll is ours regardless of latency",
               ownNotForeign);
    }
    {
        // If a foreign record wins the race after our poll, it consumes our
        // pending slot. The delayed own reply becomes the first foreign
        // sample and the next shared record still establishes the cadence.
        PollGate g;
        g.shouldPoll(0);
        g.onRecord(50);                          // foreign, classified as ours
        g.onRecord(250);                         // our delayed reply, foreign #1
        g.onRecord(350);                         // foreign #2
        report("shared polling converges after a foreign record wins the race",
               g.foreignIntervalMs() == 100 && !g.shouldPoll(400));
    }
    {
        PollGate g;
        g.onRecord(0);
        g.onRecord(100);
        const bool riding = !g.shouldPoll(150);
        g.reset();
        report("reset() clears suppression and the interval estimate",
               riding && g.shouldPoll(160) && g.foreignIntervalMs() < 0);
    }

    // ---- RangeTracker ----------------------------------------------------
    {
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        report("defaults to High with the 1500 W ceiling",
               t.displayedRange() == 0 && near(t.ceilingW(), 1500.0));
    }
    {
        // Contract High -> Low, then expand back. Expansion is immediate;
        // contraction takes kContractHoldMs.
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(2, 0.0, 0);
        const bool notYet = (t.displayedRange() == 0);
        t.onReading(2, 0.0, RangeTracker::kContractHoldMs - 1);
        const bool stillNot = (t.displayedRange() == 0);
        t.onReading(2, 0.0, RangeTracker::kContractHoldMs);
        const bool contracted = (t.displayedRange() == 2)
                                && near(t.ceilingW(), 25.0);
        t.onReading(0, 0.0, RangeTracker::kContractHoldMs + 1);
        const bool expanded = (t.displayedRange() == 0);
        report("contract needs the full hold; expand is immediate",
               notYet && stillNot && contracted && expanded);
    }
    {
        // Expansion must not require RF present. The reference flow gates on
        // power > 0.1 W, which defers an expansion arriving on the first
        // record of a transmission to the second -- the record where the wide
        // scale is most wanted.
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(2, 0.0, 0);
        t.onReading(2, 0.0, RangeTracker::kContractHoldMs);
        t.onReading(0, 0.0, RangeTracker::kContractHoldMs + 1);  // zero power
        report("expansion happens at zero power (no RF-present gate)",
               t.displayedRange() == 0);
    }
    {
        // A meter hunting between two ranges must never contract: the flow's
        // counter would expire and latch whatever a single record said.
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        for (int i = 0; i < 200; ++i) {
            t.onReading((i % 2) ? 1 : 2, 0.0, i * 100);
        }
        report("alternating range reports never contract, however long",
               t.displayedRange() == 0);
    }
    {
        // Wall-clock, not record count. The reference flow counts 20 records
        // and its own comment concedes that assumes a 100 ms poll rate; at a
        // 5 s riding-along cadence that would be minutes.
        RangeTracker fast;
        fast.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        fast.reset();
        for (int i = 0; i <= 20; ++i) { fast.onReading(2, 0.0, i * 100); }

        RangeTracker slow;
        slow.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        slow.reset();
        slow.onReading(2, 0.0, 0);
        slow.onReading(2, 0.0, 5000);   // ONE record, 5 s later
        report("contraction is wall-clock: identical at 100 ms and 5 s cadence",
               fast.displayedRange() == 2 && slow.displayedRange() == 2);
    }
    {
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 1600.0, 0);
        const bool notYet = near(t.ceilingW(), 1500.0);
        t.onReading(0, 1600.0, 100);
        const bool expanded = near(t.ceilingW(), 1600.0) && t.ceilingAutoExpanded();
        t.reset();
        const bool restored = near(t.ceilingW(), 1500.0) && !t.ceilingAutoExpanded();
        report("ceiling expands after 2 consecutive over-ceiling records, "
               "and reset() restores the configured value",
               notYet && expanded && restored);
    }
    {
        // Same up-only guard AcomConnection applies to a late SystemConfig
        // reply: a RE-READ must not shrink one that observed power has
        // already established this session. An operator EDIT is a different
        // matter and deliberately does shrink it -- see the rows below.
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 1600.0, 0);
        t.onReading(0, 1600.0, 100);
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);   // re-read of the same config
        report("a re-read ceiling does not shrink an auto-expanded one",
               near(t.ceilingW(), 1600.0));
    }
    {
        RangeTracker t;
        RangeCeilings c;
        c.highW = 700.0;
        c.midW = 125.0;
        c.lowW = 25.0;
        t.setCeilings(c, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        report("operator-configured ceilings are honoured",
               near(t.ceilingW(), 700.0));
    }

    {
        // The defect that splitting ConfigLoad from OperatorEdit fixes: with
        // one shared entry point the up-only guard swallowed a deliberate
        // edit, so an operator lowering High to match their meter saw no
        // change and got no feedback either -- the ceiling never moved, so
        // gaugeCeilingChanged() never fired.
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 1600.0, 0);
        t.onReading(0, 1600.0, 100);       // auto-expanded past 1500 W
        RangeCeilings lower;
        lower.highW = 700.0;
        t.setCeilings(lower, RangeTracker::CeilingSource::OperatorEdit, 0);
        report("an operator edit LOWERS an auto-expanded ceiling",
               near(t.ceilingW(), 700.0));
        report("and clears the auto-expanded flag with it",
               !t.ceilingAutoExpanded());
    }
    {
        // ...and the guard still holds for the path it was written for, so
        // this cannot be "simplified" back into a single code path.
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 1600.0, 0);
        t.onReading(0, 1600.0, 100);
        RangeCeilings lower;
        lower.highW = 700.0;
        t.setCeilings(lower, RangeTracker::CeilingSource::ConfigLoad);
        report("a config re-read still cannot lower it",
               near(t.ceilingW(), 1600.0));
    }
    {
        // Honouring a mistaken edit is self-correcting: real power above the
        // lowered ceiling re-expands within kCeilingExpandRecords records,
        // rather than leaving a pinned needle.
        RangeTracker t;
        RangeCeilings lower;
        lower.highW = 700.0;
        t.setCeilings(lower, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 900.0, 0);
        t.onReading(0, 900.0, 100);
        report("power above a lowered ceiling re-expands it",
               t.ceilingW() > 700.0 && t.ceilingAutoExpanded());
    }
    {
        // Editing one range must not disturb another range's scale. The menu
        // edits a single range while the gauge shows whichever the meter
        // reports, so an edit to Low used to overwrite a displayed, expanded
        // High ceiling with its unchanged configured value.
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 1600.0, 0);
        t.onReading(0, 1600.0, 100);       // High displayed, expanded to 1600
        RangeCeilings edited;
        edited.lowW = 10.0;                // a DIFFERENT range
        t.setCeilings(edited, RangeTracker::CeilingSource::OperatorEdit, 2);
        report("editing another range leaves the displayed expansion alone",
               near(t.ceilingW(), 1600.0) && t.ceilingAutoExpanded());
    }
    {
        // ...while an edit to the displayed range still lands, so the guard
        // above cannot be widened into "operator edits never apply".
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 1600.0, 0);
        t.onReading(0, 1600.0, 100);
        RangeCeilings edited;
        edited.highW = 700.0;              // the DISPLAYED range
        t.setCeilings(edited, RangeTracker::CeilingSource::OperatorEdit, 0);
        report("editing the displayed range still applies",
               near(t.ceilingW(), 700.0) && !t.ceilingAutoExpanded());
    }
    {
        // Re-entering the stored value (or Reset to defaults) is still an
        // operator action even though the RangeCeilings numbers do not
        // change. It must clear a wider session-only scale.
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 1600.0, 0);
        t.onReading(0, 1600.0, 100);
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::OperatorEdit, 0);
        report("re-entering the configured displayed ceiling clears expansion",
               near(t.ceilingW(), 1500.0) && !t.ceilingAutoExpanded());
    }
    {
        RangeTracker t;
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::ConfigLoad);
        t.reset();
        t.onReading(0, 1600.0, 0);
        t.onReading(0, 1600.0, 100);
        t.setCeilings(RangeCeilings{}, RangeTracker::CeilingSource::OperatorEdit);
        report("resetting all ranges clears displayed expansion",
               near(t.ceilingW(), 1500.0) && !t.ceilingAutoExpanded());
    }
    {
        // Regression guard for the unbounded-growth path. Once the buffer
        // starts with a marker, indexOf() always succeeds, so the no-marker
        // cap in feed() never runs again: a stream that delivers one ';' and
        // then never another used to append forever.
        ResponseParser p;
        int records = 0;
        p.setReadingCallback([&](const Reading&) { ++records; });
        p.feed(";");
        for (int i = 0; i < 200; ++i) {
            p.feed(QByteArray(64, 'x'));   // 12.8 kB, no marker, never valid
        }
        report("a stuck stream after a marker does not grow without bound",
               p.bufferedBytes() <= kRecordLength * 4 + 1);
        // And the parser is still usable once the device recovers. rec()
        // supplies the ';' -- the fixtures are bodies, not framed records.
        p.feed(rec(kCapturedIdle));
        report("and it resyncs on the next good record", records == 1);
    }

    {
        // Boundary validation. This protocol has no checksum, so
        // looksLikeRecord() is the whole integrity mechanism -- every row
        // here reached a gauge before the #5320 review.
        report("exponent notation is rejected at canonical width",
               !looksLikeRecord("01e+100,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
        report("...and at any other width",
               !looksLikeRecord("1e+100,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
        report("an over-wide power field is rejected",
               !looksLikeRecord("99999999,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
        report("an unbounded SWR is rejected",
               !looksLikeRecord("0000.00,046.3,088.5,0,NF0T  ,2,1,-2.3,1e300"));
        report("an unbounded Z is rejected",
               !looksLikeRecord("0000.00,1e300,088.5,0,NF0T  ,2,1,-2.3,1.00"));
        report("an over-long callsign is rejected",
               !looksLikeRecord(QByteArray("0000.00,046.3,088.5,0,")
                                + QByteArray(200, 'X')
                                + QByteArray(",2,1,-2.3,1.00")));
        report("a sign on an unsigned field is rejected",
               !looksLikeRecord("-000.10,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
        report("a second decimal point is rejected",
               !looksLikeRecord("00.00.0,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
        report("hex is rejected",
               !looksLikeRecord("0x10,046.3,088.5,0,NF0T  ,2,1,-2.3,1.00"));
        // ...while everything the meter really sends still decodes.
        report("the captured idle record still decodes",
               looksLikeRecord(kCapturedIdle));
        report("the captured TX record still decodes",
               looksLikeRecord(kCapturedTx));
        report("the manual's 41-char example still decodes",
               looksLikeRecord(kManualExample));
        report("dBm keeps its documented 5-char signed variant",
               looksLikeRecord("0000.00,046.3,088.5,0,NF0T  ,2,1,-12.3,1.00"));
        // No decoded field can reach the GUI as a float infinity.
        const auto r = decodeReading(kCapturedTx);
        report("a decoded reading is finite in float",
               r.has_value()
                   && std::isfinite(static_cast<float>(r->powerW))
                   && std::isfinite(static_cast<float>(r->swr))
                   && std::isfinite(static_cast<float>(r->zOhms)));
    }

    std::printf("\n%s\n", g_failed == 0 ? "all passed"
                                        : "FAILURES PRESENT");
    return g_failed == 0 ? 0 : 1;
}
